[IV-22-23] Incluida la descripcion del proyecto
MarinoFajardo/ControlaTuGasto pull request #1
Opened 2022-09-16 07:33 UTC by MarinoFajardo

Objetivo 0

2022-09-16 12:07 UTC, JJ requested changes
Por favor, mira la lista de comprobación incluida en el guión y comprueba qué es lo que cumples y lo que no.

2022-09-19 08:43 UTC, MarinoFajardo commented
[ x ] ¿Se trata de un problema real del que se tenga conocimiento personal?
     - Desde hace unos años vivo solo y tengo que tener muy bien controlado lo que gasto por lo que al ser una aplicación que 
       yo usaría le puedo dar un buen enfoque.
[ x ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
       - Sí, ya que es necesario procesar los datos obtenidos de la aplicación en un servidor.
[ x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando?
       - Sí, la aplicación analizará los datos de los clientes para aportar soluciones que le ayuden a ahorrar, ya sea proponerle 
       gasolineras más baratas o comparar precios de supermercados.
[ x ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
       -Se encuentra en la carpeta docs.

2022-09-19 08:45 UTC, MarinoFajardo commented
Tras tu comentario he revisado el guión y he añadido varias cosas. He separado el README de los demás ficheros y he enlazado lo que se pide.

2022-09-20 10:43 UTC, JJ commented
La lista de comprobación debe ir en el cuerpo del PR.

2022-09-20 10:44 UTC, JJ requested changes
Sin una identificación clara del problema es imposible que se pueda resolver mediante un programa. Por favor, consulta lo que se explicó sobre design thinking para poder llegar a entender los problemas y proponer soluciones.

2022-09-20 10:44 UTC, JJ commented on docs/DOCUMENTACION.md
> +ControlaTuGasto es una aplicación con la que podremos ir añadiendo tanto nuestros ingresos como nuestros gastos. La aplicación permitirá ir añadiendo todos los movimientos con los que gastemos dinero
Lo que se pide es un problema. Tienes que identificar claramente el problema.

2022-09-22 08:16 UTC, MarinoFajardo commented
Se ha añadido la descripción del problema a la documentación del proyecto.

2022-09-22 09:18 UTC, JJ requested changes
* No está identificado claramente el problema. Controlar los gastos no permite ahorrar, permite sólo controlar los gastos. Si la gente no ahorra no es porque no controle, es porque todo vale más. Y si lo fuera, no tienes forma de validar la solución del problema, porque nunca vas a saber si se ahorra o no.
* No tienes una forma clara de obtener los datos, por lo que también es imposible validar y testear
* No tienes una lógica de negocio. Por favor, consulta las preguntas frecuentemente preguntadas de la última versión del guión.

2022-09-23 08:19 UTC, MarinoFajardo commented
He abordado un nuevo problema y he añadido la documentación.

2022-09-24 08:36 UTC, JJ approved these changes
:+1:

2022-09-24 11:03 UTC, merged