[IV-22-23] Objetivo 3
MarinoFajardo/ControlaTuGasto pull request #20
Opened 2022-11-07 18:02 UTC by MarinoFajardo

* [ ]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un issue?
* [ ]  ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la existencia de herramientas que permitan automatizar tareas?
* [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de dependencias el que se use como gestor de tareas?
* [ ]  ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes existentes?

2022-11-14 08:28 UTC, JJ requested changes
Por favor, tratad de evitar los errores frecuentes listados en las semanas 8 a la 10.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +    - [HU001](https://github.com/MarinoFajardo/ControlaTuGasto/issues/2): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobús más b
Por favor, no metáis ruido en el PR de esta forma. Hacedlo antes o después de la revisión del objetivo.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +Tras una búsqueda para conocer los runtimes mas usados para typeScript podemos decir que los más usados son los siguientes:
Primero hay que establecer los criterios de elección y de búsqueda.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +- Otras opciones menos conocidas son: Napa.JS , Hernes , JerryScript o QuickJS, pero no son muy usadas.
Ni me sonaban. En todo caso, esto no se pedía en este objetivo.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +- NPM/PNPM: Gestor de dependencias de Node. Cuenta con un repositorio de más de 100000 paquetes y módulos.
Son diferentes.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +- Bower: Este gestor de paquetes(dependencias) corre sobre NPM. NPM es mucho más completo mientras que Bower apuesta por la reducción en el tamaño del archivo y los tiempos de carga para las dependen
No es un gestor de dependencias.

2022-11-14 08:28 UTC, JJ commented on docs/DOCUMENTACION.md
> +- RequireJS: Es un cojunto de herramientas de JS que se puede utilizar para cargar módulos de manera sencilla incluyendo módulos de Node. Puede detectar automáticamente las dependencias necesarias en
Por favor, no listéis cosas rándom y su descripción. Limitaros a establecer una serie de requisitos y poner una lista exhaustiva de los que cumplan esos requisitos.

2022-11-17 13:02 UTC, JJ requested changes
Por favor, revisa los errores frecuentes.

2022-11-17 13:02 UTC, JJ commented on docs/DOCUMENTACION.md
>  Tras elegir el gestor de Dependencias, es hora de elegir el Task Runner para la aplicación, para no aumentar la deuda técnica añadiendo nuevos ficheros a la aplicación, voy a usar yarn como Task Runn
De veras, las mayúsculas Arbitrarias...

2022-11-18 16:37 UTC, JJ requested changes
No he visto ningún cambio sustancial. Sigues teniendo que enunciar los criterios que has seguido antes de explicar los que cumplen los requisitos y de qué forman cumplen o no los criterios.

2022-11-18 16:37 UTC, JJ commented on .gitignore
> +/src/index.ts
Hay un repo con todos los .gitignore de Github. Es mejor que lo cojas de ahí.
En todo caso, no corresponde a este objetivo.
Tampoco entiendo muy bien este fichero específico, la verdad.

2022-11-18 16:37 UTC, JJ commented on docs/DOCUMENTACION.md
>  Tras elegir el Runtime que se va a usar en la aplicación, es el turno de tomar la decisión de qué gestor de dependencias se va a usar. A continuación se muestran los más comunes:
:arrow_up:

2022-11-21 10:01 UTC, MarinoFajardo commented
@JJ listo para revisión.

2022-11-21 10:03 UTC, MarinoFajardo commented on .gitignore
> +/src/index.ts
Gracias por el comentario, no conocía ese repositorio y me ha venido muy bien para añadir un buen gitignore. Lo he añadido en este objetivo ya que no lo añadí cuando hice el repositorio y pensé que era interesante añadirlo ahora para que git ignorara la carpeta node_modules. Un saludo

2022-11-21 10:10 UTC, JJ requested changes
Por favor, *saca* de este PR todo lo que no corresponda el objetivo.
Aparte de eso, ni los criterios están enunciados con precisión ni la elección hecha con respecto a los criterios enunciados. Revisa los errores frecuentes, por favor.

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +    - [HU001](https://github.com/MarinoFajardo/ControlaTuGasto/issues/2): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobús más b
:arrow_double_up:

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +Teniendo todo lo anterior en cuenta, para la aplicación se va a usar yarn debido a que su instalación no genera deuda técnica y nos da una mejora sustancial de rendimiento y seguridad con respecto a
es `pnpm`

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +A la hora de la elegir el gestor de dependencias para la aplicación es necesario establecer los criterios que que se van a tener en cuenta para esta eleción. En este caso se van a buscar gestores de
> A la hora de la elegir

No cuesta nada pegarle un repaso a lo que se envía.

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +- NPM: Gestor de dependencias por defecto de NodeJS, no nos genera deuda técnica debido a que ya viene instalado aunque ofrece un rendimiento muy bajo con respecto a pnpm y yarn.
No has dicho nada de la deuda técnica en los criterios. Hablas de "generar ficheros innecesarios". Por favor, ajustaros a los criterios que ponéis (y viceversa) y ponedlos con precisión.

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +Teniendo todo lo anterior en cuenta, para la aplicación se va a usar yarn debido a que su instalación no genera deuda técnica y nos da una mejora sustancial de rendimiento y seguridad con respecto a
Si el rendimiento es similar, ¿por qué escoges `yarn` si `pnpm` es más rápido?
Os recuerdo que no se escribe para justificar la elección que ya se ha tomado (ver errores de la semana 8), sino que se ponen los criterios y se escoge con respecto a ellos.

2022-11-21 10:10 UTC, JJ commented on docs/DOCUMENTACION.md
> +Tras elegir el gestor de Dependencias, es hora de elegir el Task Runner para la aplicación, para no aumentar la deuda técnica añadiendo nuevos ficheros a la aplicación, voy a usar yarn como Task Runn
¿`D`ependencias?
Se trata en todo caso, como se ha repetido muchas veces, que pongáis los criterios y mostréis que conocéis el panorama y las opciones posibles.

2022-11-21 10:10 UTC, JJ commented on package.json
> +  "main": "index.js",
No tienes ningún fichero main.

2022-11-21 10:10 UTC, JJ commented on src/ruta.ts
> +    private origenRuta: Parada;
Esto no corresponde a este objetivo.

2022-11-21 10:11 UTC, JJ commented on .gitignore
> +/src/index.ts
Como te he dicho en el comentario, preferiría que sólo incluyérais en el PR lo que sea evaluable para el mismo. Sacad este fichero (y el resto) en otro PR para que no aparezca aquí, ya que sólo añade ruido para el revisor.

2022-11-21 12:51 UTC, MarinoFajardo commented
@JJ listo para revisión.

2022-11-21 13:13 UTC, JJ requested changes
Por favor, no os inventéis cosas. "Más estandarizados" ni siquiera existe como concepto, mucho menos para un criterio. Y mirad lo que mide Snyk y reflejadlo con exactitud. O simplemente si son criterios que no habéis usado (que está claro que no lo habéis hecho, porque lo acabáis de meter en el último commit y no habéis cambiado la elección) simplemente no lo pongáis.

2022-11-21 13:13 UTC, JJ commented on README.md
> +## Comprobaciones
No son comprobaciones, es la instalación. Habrá también que instalar `pnpm`, ¿no? Ya os puse en la semana 10 que debíais poner instrucciones completas.

2022-11-21 13:13 UTC, JJ commented on docs/DOCUMENTACION.md
> +A la hora de elegir el gestor de dependencias para la aplicación es necesario establecer los criterios que se van a tener en cuenta para esta elección. En este caso se van a buscar gestores de depend
¿Qué tiene que ver Snyk con "más estandarizados"?

2022-11-21 13:13 UTC, JJ commented on docs/DOCUMENTACION.md
> +Para la elección del gestor de tareas se va a tener en cuenta su lo estandarizada que esté la herramienta. Al igual que para el gestor de dependencias, la estandarización de la herramienta se va a me
"su lo"
¿Qué significa "lo estandarizada que esté"? O es estándar o no lo es.

2022-11-24 09:35 UTC, MarinoFajardo commented
@JJ listo para revisión.

> Por favor, no os inventéis cosas. "Más estandarizados" ni siquiera existe como concepto, mucho menos para un criterio. Y mirad lo que mide Snyk y reflejadlo con exactitud. O simplemente si son criterios que no habéis usado (que está claro que no lo habéis hecho, porque lo acabáis de meter en el último commit y no habéis cambiado la elección) simplemente no lo pongáis.

En este caso lo incluí debido a que en la revisión anterior me comentaste que no estaba estableciendo los criterios de forma correcta, en mi caso este criterio aunque lo añadí en la última revisión me ha hecho cambiar de decisión, ya que antes estaba usando yarn como gestor de dependencias únicamente por ser más rápido que npm y tener un rendimiento similar en algunas cosas a pnpm sin tener en cuenta que lleva 6 meses sin actualizarse.

2022-11-24 11:05 UTC, JJ commented
[yarn tiene 85 de puntuación](https://snyk.io/advisor/npm-package/yarn). Tampoco creo que sea como para echarse las manos a la cabeza.

2022-12-01 11:31 UTC, JJ approved these changes
👍 Y perdona la tardanza; mi compromiso es corregirlo en 2 o 3 días laborables, si no lo hago por favor recordádmelo.

2022-12-01 11:32 UTC, merged