[IV-22-23] Objetivo 4
MarinoFajardo/ControlaTuGasto pull request #30
Opened 2022-12-02 09:42 UTC by MarinoFajardo

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de usuario que desarrolla, pasando por el mensaje de commit y el issue correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases, módulos o paquetes más fundamentales frente a otros, movidos a otro PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y del de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo `unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se considere viable?
* [ ] ¿Se han testeado también las excepciones?

2022-12-15 13:17 UTC, JJ requested changes
Como te he comentado, el grueso tiene buena pinta. Pero:
1. Tienes que plantear el problema correctamente para poder escribir tests correctos (en su propio issue, como siempre)
2. En ese sentido, en el planteamiento del problema tienes que poner más comportamientos que luego vayas a usar en los tests.
3. Los datos de test tienen que estar separados de los datos del problema
4. Tampoco puedes poner constantes en el código, sólo en los tests.

2022-12-16 12:06 UTC, JJ requested changes
Hay varios problemas, pero el principal es que tienes que plantear los problemas en issues para poder resolverlos correctamente. De ahí viene la complejidad del código para lo que se intenta hacer.

2023-01-09 16:13 UTC, MarinoFajardo commented
Como los issues no están bien planteados, voy a marcarlos como inválidos los que se han realizado hasta ahora y voy a crear nuevos para plantear mejor el problema.

2023-01-10 12:29 UTC, MarinoFajardo commented on babel.config.js
> +module.exports = {
He estado mirando cosillas y para instalar typescript con Jasmine también es necesaria la instalación de Webpack, por lo que al final hay que instalar herramientas adicionales uses lo que uses.

2023-01-10 13:28 UTC, JJ commented on babel.config.js
> +module.exports = {
Igualmente, si tienes que instalar todo eso igual no es la mejor opción.

2023-01-10 13:29 UTC, JJ commented on src/algoritmo.ts
> +      for(let tramo of tramos){
El resultado del bucle es constante, no varía de una invocación de la función a la siguiente.

2023-01-10 13:38 UTC, MarinoFajardo commented on src/algoritmo.ts
> +      for(let tramo of tramos){
Vale, me había dado cuenta de eso esta mañana y lo estaba arreglando, gracias, pensaba que te referías a que siempre recorría todos los tramos del Json, ahora lo entiendo.

2023-01-11 16:46 UTC, JJ commented on README.md
> +## Ejecución de los test
Las instrucciones tienen que ser completas y precisas. ¿`pnpm` lo tiene instalado todo el mundo? ¿Donde dice `instalación de pnpm`, efectivamente estás diciendo cómo se instala `pnpm`?

2023-01-11 16:47 UTC, JJ commented on docs/DOCUMENTACION.md
> +## Test Runner
NO entiendo por qué comienzas con el test runner, cuando la primera biblioteca que se va a usar va a ser la de aserciones.

2023-01-11 16:52 UTC, JJ commented on docs/DOCUMENTACION.md
> +- **Jasmine**: Trae incluida una biblioteca de aserciones, por lo que ya no sería necesaria su incorporación, su última actualización se realizó hace 26 días y usa BDD aunque también puede usar unite
Hay dos módulos que se llaman jasmine, uno de ellos es `jasmine-core`. Si no enlazas de qué estás hablando (lo que tendrías que hacer de todas formas, aunque no fuera ambiguo) es imposible saber si estás incluyendo aquí algo que corresponda o no.
Por lo que estoy viendo, no sería un test runner para cualquier biblioteca, sino que serviría sólo y exclusivamente para ejecutar tests en jasmine. Lo puedes leer en la misma descripción en la web.

2023-01-11 16:53 UTC, JJ commented on docs/DOCUMENTACION.md
> +- **Jest**: Al igual que Jasmine trae incorporada su propia biblioteca de aserciones, por lo que no sería necesario incluir más herramientas a la aplicación. Su última actualización fue hace 16 días
Typescript no es un intérprete. Y si es obligatorio usar Babel para esto, entonces el runner que estás eligiendo es la combinación de los dos. Y una vez más, si tu requisito es que haya que incluir el mínimo número de herramientas, no sería el más adecuado.

2023-01-11 16:54 UTC, JJ commented on docs/DOCUMENTACION.md
> +Teniendo todo esto en cuenta y conociendo que será necesaria la instalación de un intérprete para Typescript, voy a optar por usar Jest. Se podría haber optado igualmente por Jasmine, ya que cumple t
Podías poner la puntuación de cada uno, y enlace. No entiendo por qué no ponéis ninguno una tabla con las medidas en las características que queréis.

2023-01-11 16:56 UTC, JJ commented on docs/DOCUMENTACION.md
> +- **Jest**: Al igual que Jasmine trae incorporada su propia biblioteca de aserciones, por lo que no sería necesario incluir más herramientas a la aplicación. Su última actualización fue hace 16 días
Adicionalmente, no necesitas Babel para esto. simplemente `ts-jest`. Por favor, infórmate bien de las herramientas antes de la elección de las mismas.

2023-01-11 16:57 UTC, JJ commented on package.json
> +    "@babel/core": "^7.20.5",
:arrow_up:

2023-01-11 16:57 UTC, JJ commented on src/data/datos.json
> +[
Si son datos de test, metedlos en el directorio de test.

2023-01-11 16:58 UTC, JJ commented on src/test/algoritmo.test.ts
> +test("El peso del árbol genrado para calcular las rutas entre Granada y Otívar tiene un peso de 13",() => {
typo. También repites peso

2023-01-12 07:42 UTC, JJ requested changes
No has respondido a las objeciones anteriores, y sigues sin realizar el proceso de elección de las herramientas necesarias adecuadamente.

2023-01-12 07:42 UTC, JJ commented on README.md
> +## Ejecución de los test
:arrow_up: 
Os agradecería que contestárais a todas las objeciones antes de solicitar revisión de nuevo.

2023-01-12 07:42 UTC, JJ commented on docs/DOCUMENTACION.md
> +## Test Runner
:arrow_up:

2023-01-12 07:42 UTC, JJ commented on docs/DOCUMENTACION.md
> +Teniendo todo lo anterior en cuenta, voy a optar por usar Jest en la aplicación, ya que requiere únicamente de la instalación de ts-jest mientras que Jasmine requiere la instalación de más herramient
Teniendo en cuenta todo lo anterior `mocha` tiene más puntuación. Y no has tenido en cuenta lo más importante, que es que funcione con Typescript.
De verdad que os agradecería que os tomárais en serio el proceso de elección de herramientas, y no os limitárais a escribir cosas para justificar una elección que habéis hecho de antemano.

2023-01-12 07:42 UTC, JJ commented on iv.yaml
> +  - /src/test/algoritmo.test.ts
Este path absoluto es incorrecto.

2023-01-12 07:42 UTC, JJ commented on package.json
> +    "start": "ts-node ./src/algoritmo.ts",
¿Para qué sirve este objetivo?

2023-01-13 18:41 UTC, MarinoFajardo commented on package.json
> +    "start": "ts-node ./src/algoritmo.ts",
Lo usaba para ejecutar cosas en algoritmo.ts para probar el árbol.

2023-01-13 18:44 UTC, MarinoFajardo commented on README.md
> +## Ejecución de los test
En la última actualización del README añadí un enlace para instalar pnpm. ¿Lo añado en el README directamente o lo puedo dejar en el enlace?

2023-01-13 18:53 UTC, MarinoFajardo commented
@JJ listo para revisión. He contestado a todas las objeciones de la revisión anterior. Lo único que como te comento, añadí la instalación de pnpm en un link en el README y no se si añadirlo directamente o dejarlo en el enlace. Un saludo.

2023-01-13 19:44 UTC, JJ commented on package.json
> +    "start": "ts-node ./src/algoritmo.ts",
Para eso es para lo que están los tests. Si los tests no hacen eso, es que están mal.

2023-01-16 07:10 UTC, JJ requested changes
Dos problemas principales
* El planteamiento de la elección de herramientas, que no es adecuado al lenguaje elegido
* La modelozación del problema, que no sigue la metodología adecuada.

2023-01-16 07:10 UTC, JJ commented on src/test/algoritmo.test.ts
> +const arbol:Arbol = new Arbol(raiz,destino,array);
Mirando a los tests, estás exponiendo muchos detalles de implementación que no tienen por qué ser obvios para el usuario. Una buena implementación de la lógica de negocio crea una capa de abstracción que deja al usuario-desarrollador preocuparse solamente del resultado a su problema. En este caso, aparentemente, tienes que crear Nodos, de elllos árboles, y solo en ese momento se puede empezar a llamar a la ruta

2023-01-16 07:10 UTC, JJ commented on src/algoritmo.ts
> +export function rutaMasBarata(origen : string , destino: string, arbol: Arbol, tramos:Tramo[]):number{
Si te ves a ti mismo pasando repetidamente argumentos a funciones, es que estás usando un nivel de abstracción inadecuado y lo que necesitas es un objeto que lo use como atributo.

2023-01-16 07:11 UTC, JJ commented on docs/DOCUMENTACION.md
> +Teniendo todo lo anterior en cuenta, voy a optar por usar Jest en la aplicación, ya que requiere únicamente de la instalación de ts-jest mientras que Jasmine requiere la instalación de más herramient
Ya te dije aquí que debías tener en cuenta si funcionaban o no con TypeScript. Es lo más importante, de hecho.

2023-01-24 16:05 UTC, MarinoFajardo commented
@JJ Listo para revisión.

2023-01-24 16:25 UTC, JJ approved these changes
Habría algunas cosas que hacer antes del siguiente, y sobre todo atender a todas las sugerencias, pero el objetivo de aprendizaje está superado.

2023-01-24 16:25 UTC, JJ commented on README.md
>  ## Instalación de pnpm
¿Quieres decir que para instalar pnpm hay que usar `pnpm install`?

2023-01-24 16:25 UTC, JJ commented on README.md
> +## Ejecución de los test
Por favor, lee lo que estoy diciendo. En el apartado que pone "instalación de pnpm` no es eso lo que hace.

2023-01-24 16:25 UTC, JJ commented on package.json
> +    "@types/node": "^18.11.18"
¿Seguro que es dependencia de producción?

2023-01-24 16:25 UTC, JJ commented on src/algoritmo.ts
> +export function obtenerNodoRaíz(origen:string,tramos:Tramo[]): Nodo{
:arrow_up:

2023-01-24 16:25 UTC, JJ commented on src/algoritmo.ts
> +  let nodo : Nodo = {
¿Esto es una constante? Si lo es, usa una constante.

2023-01-24 16:25 UTC, JJ commented on src/algoritmo.ts
> +  let minimo : number = 100;
¿Constante?

2023-01-24 16:25 UTC, JJ commented on src/test/sanity.test.ts
> +    expect(tramos.length).to.equal(totalTramos);
Esto no testea ningún comportamiento.

2023-01-26 11:42 UTC, merged