[IV-22-23]Objetivo 1
MarinoFajardo/ControlaTuGasto pull request #5
Opened 2022-10-06 10:37 UTC by MarinoFajardo

Milestones:
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
   Sí.
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
   Los milestones van en orden ascendente de dificultad y para pasar al siguiente hay que realizar el anterior.
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
   Sí.
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
   No, pero se explica que para poder llevar a cabo la primera historia de usuario es necesario realizar el milestone 0.
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
   Sí, con ese milestone se pretende crear los ficheros necesarios para representar las estructuras de datos necesarias.
* [x] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
   Sí.
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
   En mi caso hay varios milestones que van avanzando el trabajo poco a poco y no hay un gran salto enre ellos.
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
   Sí, en los primeros milestones se crean las estructuras de datos y en los finales se resuelven los problemas de las historias de usuario.
* [x]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
  Sí.
* [x]  ¿El milestone 0 es mínimo *y* viable?
  Sí
* [x]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
  Si.
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
    Como los milestones van avanzando poco a poco sobre la funcionalidad, no podrían haber PMV entre milestones y milestones.

Historias de Usuario:
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
  Sí, están descritos en la documentación del proyecto.
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo? 
   Sí.
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
  Cada historia de usuario trata sobre un problema que el cliente desea resolver y va ligado con la lógica de negocio.

2022-10-07 07:32 UTC, MauronMP commented
Buenas @MarinoFajardo, me ha tocado como revisor de tu objetivo 1, he visto que quizás tendrías que decir quién es el cliente final y en los milestones [M2](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/4), [M3](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/5) y [M4](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/6), ¿qué le vas a dar al cliente final cuando hayas hecho los cálculos, un documento, un mensaje?

2022-10-07 07:47 UTC, MarinoFajardo commented
Buenas @MauronMP, ya he añadido lo que me has comentado.

2022-10-10 10:00 UTC, MauronMP commented on docs/DOCUMENTACION.md
> +    -[HU001](https://github.com/MarinoFajardo/ControlaTuGasto/issues/2): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobuús más b
Viendo lo que nos dijo JJ sobre quién era el cliente, puede ser tanto ese como un usuario que vaya de viajes, así que lo pondría por si acaso.

2022-10-10 10:01 UTC, MauronMP commented on docs/DOCUMENTACION.md
> +    -[HU002](https://github.com/MarinoFajardo/ControlaTuGasto/issues/3): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobuús más c
Lo mismo mencionado en la HU001 con el cliente

2022-10-10 10:01 UTC, MauronMP commented on docs/DOCUMENTACION.md
> +    -[HU003](https://github.com/MarinoFajardo/ControlaTuGasto/issues/4): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobuús más ó
Lo mismo mencionado en la HU001 con el cliente

2022-10-10 10:07 UTC, MauronMP commented on docs/DOCUMENTACION.md
> +    -[M1](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/3): Con este milestone se pretende crear los ficheros correspondientes que permitan recoger los datos referentes a las rutas de au
En este milestone no sé realmente qué quieres hacer, ya que en los milestone M2, M3 y M4 ya creas ficheros para procesar los datos y en M0 ya tienes tu estructura de datos usando unos datos ya existentes de la junta. Puede ser que no lo entienda desde mi punto de vista.

2022-10-10 10:08 UTC, MauronMP commented on docs/DOCUMENTACION.md
> +    -[M4](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/6): Con este milestone se pretende crear los ficheros correspondientes para procesar los datos referentes a las rutas de autobuses
Tanto en M2 como en M3 y M4, ¿tienes pensado más o menos que procesamiento de datos quieres usar?

2022-10-10 10:09 UTC, MauronMP reviewed
He sugerido unos cambios (no sé si están bien mi punto de vista)

2022-10-10 13:29 UTC, MarinoFajardo commented on docs/DOCUMENTACION.md
> +    -[M1](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/3): Con este milestone se pretende crear los ficheros correspondientes que permitan recoger los datos referentes a las rutas de au
En el milestone 1 lo que pretendo hacer es crear una biblioteca con la que poder recoger los datos de las rutas, por ejemplo, si yo creo una clase que se llame tramo, crear las funciones necesarias para crear esos tramos a partir de los datos de la Junta.

2022-10-10 13:31 UTC, MarinoFajardo commented on docs/DOCUMENTACION.md
> +    -[M4](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/6): Con este milestone se pretende crear los ficheros correspondientes para procesar los datos referentes a las rutas de autobuses
Voy a crear tramos entre el lugar de origen y el destino que generarán un grafo. Sobre este grafo aplicaré un algoritmo greedy que en cada caso proporcionará la ruta que estamos buscando.

2022-10-10 13:34 UTC, MarinoFajardo commented
@MauronMP Buenas, acabo de corregir lo que me has comentado.

2022-10-10 13:56 UTC, MauronMP commented
Buenas @MarinoFajardo, por lo que me has dicho me parece entonces que está bien, lo pondré para que JJ lo revise entonces.

2022-10-10 13:57 UTC, MauronMP approved these changes

2022-10-10 14:00 UTC, MauronMP approved these changes
Comprobado para que JJ lo revise

2022-10-10 15:08 UTC, MarinoFajardo commented
@jj

2022-10-10 15:15 UTC, JJ requested changes
Por favor, revisa la secuencia y contesta también a las objeciones que te ha hecho @MauronMP con cambios en la documentación.

2022-10-10 15:15 UTC, JJ commented on docs/DOCUMENTACION.md
> +## Objetivo 1
No hace falta que pongáis esto en la documentación. Ya se sabe de qué objetivo son por el PR

2022-10-10 15:15 UTC, JJ commented on docs/DOCUMENTACION.md
> +    -[HU002](https://github.com/MarinoFajardo/ControlaTuGasto/issues/3): Con esta historia de usuario queremos resolver el problema que se nos plantea a la hora de encontrar la ruta de autobús más co
Las HU van cambiando de milestone, ya lo he dicho en clase. No vas a resolver ninguna HU cuando acabes ningún milestone (en esta asignatura)

2022-10-10 15:15 UTC, JJ commented on docs/DOCUMENTACION.md
> +    -[M0](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/2): Con este milestone interno se pretende crear un producto que contenga una serie de ficheros para resolver la parte de la lógic
Si no tienes un modelo del problema, no puedes aplicar la lógica de negocio. También lo hemos dicho en clase repetidamente.

2022-10-10 15:15 UTC, JJ commented on docs/DOCUMENTACION.md
> +    -[M1](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/3): Con este milestone se pretende crear los ficheros correspondientes que permitan recoger los datos referentes a las rutas de au
¿Seguro que esa secuencia está correcta?

2022-10-10 15:15 UTC, JJ commented on docs/DOCUMENTACION.md
> +    -[M4](https://github.com/MarinoFajardo/ControlaTuGasto/milestone/6): Con este milestone se pretende crear los ficheros correspondientes para procesar los datos referentes a las rutas de autobuses
Por un lado, cuando se hace una revisión no es para que lo aclares en la contestación, sino en lo que se está revisando. Por otro lado, los milestones no necesitan tener necesariamente más "procesamiento", pero tienen que estar en la secuencia correcta.

2022-10-11 09:41 UTC, JJ requested changes
La secuencia sigue siendo inadecuada, y también poner "los ficheros corresondientes a" no convierte a algo en producto automáticamente.

2022-10-13 11:07 UTC, JJ approved these changes
👍

2022-10-13 11:07 UTC, merged