Objetivo 5
MarinoFajardo/ControlaTuGasto pull request #59
Opened 2023-01-26 12:44 UTC by MarinoFajardo

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así como los criterios de búsqueda que han conducido a las imágenes que se están considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto tiene una función específica, tal como testear cómo va en la última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha comprobado que lo que se instale sea sólo y exclusivamente lo necesario para nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el directorio que monta, ya que no tiene derecho de escritura?

2023-01-26 12:52 UTC, MarinoFajardo commented
@JJ, el pull request del objetivo me ha dado fallo porque aún no tengo configurado el contenedor, te escribo para ver si podrías echarle un vistazo a la elección de la imagen base y saber si es correcta para no trabajar sobre algo que no es correcto. Un saludo.

2023-01-26 13:35 UTC, JJ commented
> @JJ, el pull request del objetivo me ha dado fallo porque aún no tengo configurado el contenedor, te escribo para ver si podrías echarle un vistazo a la elección de la imagen base y saber si es correcta para no trabajar sobre algo que no es correcto. Un saludo.

¿Por qué no miras los errores frecuentes y la lista de comprobación? Si tienes alguna duda, también está el grupo de Telegram.

2023-02-07 18:21 UTC, Carlos-SE requested changes
Buenas, se me ha asignado a tu PR para revisarlo, espero poder echarte una mano :smile:
Te dejo un par de comentarios sobre cosas que puedes mejorar o investigar más.

Cualquier cosa me escribes!

2023-02-07 18:23 UTC, Carlos-SE requested changes
Buenas, se me ha asignado a tu PR para revisarlo, espero poder echarte una mano smile
Te dejo un par de comentarios sobre cosas que puedes mejorar o investigar más.

Cualquier cosa me escribes!

2023-02-07 18:23 UTC, Carlos-SE commented on docs/DOCUMENTACION.md
> +  - **node:lts-slim**: Imagen node:lts que contiene únicamente los paquetes necesarios para instalar node. Tiene un peso comprimido de 75.97 MB y su última actualización fue hace 15 días.
Las versiones lts no usan la última versión disponible de node, tenlo en cuenta. Además, ¿estás seguro de que sólo instala lo necesario para instalar node? Te recomiendo mirar [su repositorio](https://github.com/nodejs/docker-node/blob/f996e97a2e6d2aae2de3b869e083a253733f07a8/18/bullseye-slim/Dockerfile) para ver las herramientas que utilizan.

2023-02-07 18:23 UTC, Carlos-SE commented on Dockerfile
> +COPY --chown=node:node . .
¿Necesitas copiar todos los archivos del directorio raíz dentro del contenedor?

2023-02-07 18:29 UTC, MarinoFajardo commented on docs/DOCUMENTACION.md
> +  - **node:lts-slim**: Imagen node:lts que contiene únicamente los paquetes necesarios para instalar node. Tiene un peso comprimido de 75.97 MB y su última actualización fue hace 15 días.
Instala cosas que no son necesarias también, como yarn(uso pnpm), pero por lo que he estado mirando todas estas imágenes de node lo traen instalado también.

2023-02-07 18:34 UTC, MarinoFajardo commented on Dockerfile
> +COPY --chown=node:node . .
He estado usando este [enlace](https://www.digitalocean.com/community/tutorials/como-crear-una-aplicacion-node-js-con-docker-es) para la creación del dockerfile. Según el enlace, esta orden se usa para garantizar que todos los archivos son propiedad del usuario no root node. Quizá está página no sea correcta del todo y no haya que hacerlo.

2023-02-07 18:35 UTC, Carlos-SE commented on docs/DOCUMENTACION.md
> +  - **node:lts-slim**: Imagen node:lts que contiene únicamente los paquetes necesarios para instalar node. Tiene un peso comprimido de 75.97 MB y su última actualización fue hace 15 días.
Las cosas que no uses sólo generan deuda técnica y aumentan el peso innecesariamente aunque sea muy poco.

> - [X]  ¿La imagen incluye sólo y exclusivamente la infraestructura necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha comprobado que lo que se instale sea sólo y exclusivamente lo necesario para nuestro proyecto?

No instala sólo y exclusivamente lo necesario para tu proyecto.

2023-02-07 18:38 UTC, Carlos-SE commented on Dockerfile
> +COPY --chown=node:node . .
La parte de la instrucción que es `--chwon=node:node` sirve para eso. A lo que me refiero es que estás copiando todo tu repositorio dentro del contenedor.

Ten en cuenta que a la hora de ejecutarlo, se hará montando el volumen de tu repo en la dirección  /app/test, de forma que tendrás los ficheros dentro durante la ejecucción, pero para construir el Docker no te hacen falta todos los ficheros

2023-02-07 18:39 UTC, Carlos-SE commented on Dockerfile
> +WORKDIR /home/node/app
Fíjate en el guión de la práctica el directorio en el que se montan el volumen.

2023-02-09 09:07 UTC, MarinoFajardo commented
He tenido un error al referenciar el último commit y he referenciado #65 en vez de #68

2023-02-09 09:08 UTC, MarinoFajardo commented
@Carlos-SE ya he modificado los errores que me comentabas, un saludo.

2023-02-09 09:35 UTC, Carlos-SE commented
> @Carlos-SE ya he modificado los errores que me comentabas, un saludo.

Buenas! Lo de la versiones lts que te comenté lo descartas? Ten en cuenta que no usan node 19, que es la última versión. Y también te instala cosas que no usas. El Dockerfile ya parece estar correcto :+1:

2023-02-09 09:46 UTC, MarinoFajardo commented
@Carlos-SE en el caso de las versiones prefiero optar por una versión lts antes que por una latest, ya que las lts contienen las última versión estable de Node y las latest contienen la última versión, que no son estables y pueden generar errores.

2023-02-09 09:47 UTC, MarinoFajardo commented
@JJ Listo para revisión

2023-02-09 09:55 UTC, JJ commented
> @Carlos-SE en el caso de las versiones prefiero optar por una versión lts antes que por una latest, ya que las lts contienen las última versión estable de Node y las latest contienen la última versión, que no son estables y pueden generar errores.

No son incompatibles, puedes tener una lts y también latest y de hecho la lista de comprobación te guía para que lo hagas.
En todo caso, es un contenedor de test.

2023-02-09 10:01 UTC, JJ requested changes
Aparte de lo indicado, que es bastante, es conveniente que mires todas las imágenes, no sólo las oficiales, como repetimos en clase muchas veces.

2023-02-09 10:01 UTC, JJ commented on Dockerfile
> +RUN npm install -g pnpm \
¿En qué directorio estás copiando esto? ¿Dónde crea los módulos y demás?

2023-02-10 08:33 UTC, MarinoFajardo commented
@JJ Listo para revision

2023-02-10 15:53 UTC, JJ requested changes
Por favor, mira todos los comentarios que se te han hecho.

2023-02-10 15:53 UTC, JJ commented on Dockerfile
> +ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
... Que siguen ahí.

2023-02-10 15:53 UTC, JJ commented on Dockerfile
> +    && pnpm install \
¿Dónde instala esto los módulos?

2023-02-10 15:53 UTC, JJ commented on Dockerfile
> +    && rm package.json pnpm-lock.yaml
¿Con qué usuario lo estás ejecutando?

2023-02-10 15:53 UTC, JJ commented on docs/DOCUMENTACION.md
> +- La imagen debe contar con actualizaciones freuentes para no generar deuda técnica.
typo

2023-02-10 15:53 UTC, JJ commented on docs/DOCUMENTACION.md
> + ### Imagenes Oficiales de Node:
Error de markdown

2023-02-10 17:54 UTC, MarinoFajardo commented
@JJ he corregido los errores de la documentación, he unido las 3 sentencias ENV en una sola y he cambiado al usuario genérico de la imagen antes de realizar las instalaciones. Además, he movido la copia y la instalación de los módulos a /app(antes se hacía en la raíz). Creo que es todo lo que me has comentado. Un Saludo.

2023-02-11 10:04 UTC, JJ approved these changes
:+1: , pero sólo porque es la última oportunidad. Varios comandos que has puesto no evidencian que tengas clara la secuencia de lo que haces, las buenas prácticas, ni dónde estás cuando ejecutas cada orden (por ejemplo, uso de caminos absolutos y relativos).  Te habría agradecido también que no lo hicieras a última hora del viernes.

2023-02-11 10:04 UTC, JJ commented on Dockerfile
> +
Siempre conviene que pongáis el comando lo más cerca posible de donde se afecta. `WORKDIR` no afecta `ENV`, por lo que no tiene mucho sentido ponerlo justo encima.

2023-02-11 10:04 UTC, JJ commented on Dockerfile
> +RUN mkdir -p /app/test
No es necesario que crees este directorio, se crea automáticamente cuando lo montas. Tienes el efecto secundario de crear `/app`, que sí que lo usas.

2023-02-11 10:04 UTC, JJ commented on Dockerfile
> +    && rm /app/package.json /app/pnpm-lock.yaml
¿En qué directorio estás? ¿Vas a necesitar el path absoluto para borrar?

2023-02-11 10:22 UTC, merged